name:          Baseline
title:         Baseline, A Component Library from 10up
description:   Front-end components for 10up.
url:           https://10up.github.io/
baseurl:       /wp-component-library
permalink: none
author:
  name:    10up
  email:   sales@10up.com
  github:  10up
  twitter: 10up
encoding:      utf-8
markdown:      kramdown
highlighter:   rouge
kramdown:
  input: GFM
sass:
  sass_dir: assets/css/sass
collections:
  component:
    output: true
